import StoryblokProvider from '@/components/StoryblokProvider';
import { getStoryblokApi } from '@storyblok/react/rsc';
import { StoryblokServerComponent } from '@storyblok/react/rsc';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
	const currentYear = new Date().getFullYear();

	const storyblokApi = getStoryblokApi();
	const { data } = await storyblokApi.get('cdn/stories/config', {
		version: 'draft',
		resolve_links: 'url',
	});

	const config = data.story.content;
	const footerBlok = config.footer?.[0];

	return (
		<StoryblokProvider>
			<html lang="en">
				<body>
					{children}
					{footerBlok && <StoryblokServerComponent blok={footerBlok} />}
				</body>
			</html>
		</StoryblokProvider>
	);
}
